version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/one"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/two"
    schedule:
      interval: "daily"
